name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # jalan otomatis setiap hari
  workflow_dispatch: {}    # bisa dijalankan manual dari tab Actions
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          config_display: large
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming, markup
          plugin_languages_limit: 8
